apiVersion: frrk8s.metallb.io/v1beta1
kind: FRRConfiguration
metadata:
  name: tenant2
  namespace: openshift-frr-k8s
  labels:
    routeAdvertisements: tenanats-frr
spec:
  nodeSelector: {}
  bgp:
    routers:
    - asn: 65002
      vrf: tenant2-net
      neighbors:
      - address: 10.0.5.12
        asn: 65001
        disableMP: true
        dualStackAddressFamily: false
        toReceive:
          allowed:
            mode: filtered
